chore: update deployment triggers, optimize container metadata, and improve dependency installation logic

diff --git a/root/etc/s6-overlay/s6-rc.d/deps-install/run b/root/etc/s6-overlay/s6-rc.d/deps-install/run
--- a/root/etc/s6-overlay/s6-rc.d/deps-install/run
+++ b/root/etc/s6-overlay/s6-rc.d/deps-install/run
@@ -8,6 +8,11 @@ if [ "$MODE" == "production" ]; then
 	exit 0
 fi
 
+if [ ! -f "requirements.txt" ]; then
+	ERROR "Error: requirements.txt not found" >&2
+	exit 1
+fi
+
 
 
 if [ -f ".requirements.lock" ] \
@@ -23,11 +28,6 @@ fi
 
 SUCCESS "**** Installing dependencies... ****"
 
-if [ ! -f "requirements.txt" ]; then
-	ERROR "Error: requirements.txt not found" >&2
-	exit 1
-fi
-
 if [ ! -f "$VIRTUAL_ENV/bin/activate" ]; then
 	uv venv "$VIRTUAL_ENV"
 fi
@@ -35,3 +35,4 @@ fi
 uv pip install --link-mode=copy --no-cache -r requirements.txt
 sha256sum requirements.txt > .requirements.lock
 cp .requirements.lock "$VIRTUAL_ENV/.requirements.lock"
+chown abc:abc .requirements.lock
