chore: local 모드 추가, manage 엔드포인트 추가 (#9)
* fix: ZeroDivisionError

* feat: GET /seeds/status - 시드 데이터 개수 조회

* refactor: prod/dev 탐지 문제 해결하기 위해 빌드 환경 재설계

- docker/build-push-action에 캐시 적용
- 환경변수 APP_ENV를 MODE로 변경
- prod/dev 2단계 스테이징 -> local 스테이징 추가
  - 기존의 dev기 local임
  - 변경된 dev는 이전의 dev와 100% 호환

* reactor: manage 라우터 추가 및 seeds를 manage 하위로 이동

* feat: 일부 scripts를 manage 엔드포인트로 등록

- insert-data, drop-to-seeds, download-data를 컨테이너로 실행 가능하도록 변경
- drop-to-seeds를 제외한 모든 파이썬 스크립트
- delete /seeds -> 백그라운드 실행이 아닌 즉시 실행 및 응답

* test: test_mode.py 수정 및 test_manage.py 추가

* build: 도커 이미지에 label 및 GPL 3.0 적용

* refactor: config/redis tab -> 4 space

diff --git a/root/etc/s6-overlay/s6-rc.d/deps-install/run b/root/etc/s6-overlay/s6-rc.d/deps-install/run
--- a/root/etc/s6-overlay/s6-rc.d/deps-install/run
+++ b/root/etc/s6-overlay/s6-rc.d/deps-install/run
@@ -1,17 +1,37 @@
 #!/usr/bin/with-contenv bash
 
+source "/app/scripts/functions.sh"
+
 cd /app
 
-if [ "$APP_ENV" != "production" ]; then
-	echo "**** Installing dependencies... ****"
-
-	if [ ! -f "requirements.txt" ]; then
-		echo "Error: requirements.txt not found" >&2
-		exit 1
-	fi
-
-	if [ ! -f "$VIRTUAL_ENV/bin/activate" ]; then
-		uv venv "$VIRTUAL_ENV"
-	fi
-	uv pip install --no-cache -r requirements.txt
+if [ "$MODE" == "production" ]; then
+	exit 0
 fi
+
+
+
+if [ -f ".requirements.lock" ] \
+&& [ -f "$VIRTUAL_ENV/.requirements.lock" ] \
+&& diff .requirements.lock "$VIRTUAL_ENV/.requirements.lock" > /dev/null \
+&& sha256sum -c .requirements.lock --quiet 2> /dev/null \
+; then
+	INFO "Skipping dependency installation, requirements.txt has not changed."
+	exit 0
+fi
+
+
+
+SUCCESS "**** Installing dependencies... ****"
+
+if [ ! -f "requirements.txt" ]; then
+	ERROR "Error: requirements.txt not found" >&2
+	exit 1
+fi
+
+if [ ! -f "$VIRTUAL_ENV/bin/activate" ]; then
+	uv venv "$VIRTUAL_ENV"
+fi
+
+uv pip install --link-mode=copy --no-cache -r requirements.txt
+sha256sum requirements.txt > .requirements.lock
+cp .requirements.lock "$VIRTUAL_ENV/.requirements.lock"
